-- sample-database.sql — esquema mínimo + dados de exemplo
SET NAMES utf8mb4;
SET time_zone = '+00:00';


CREATE TABLE IF NOT EXISTS usuarios (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(120) NOT NULL,
email VARCHAR(160) NOT NULL UNIQUE,
senha_hash VARCHAR(255) NOT NULL,
perfil ENUM('admin','editor','usuario') DEFAULT 'admin',
criado_em DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS lojas (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(160) NOT NULL,
slug VARCHAR(160) NOT NULL UNIQUE,
url VARCHAR(255) DEFAULT NULL,
logo VARCHAR(255) DEFAULT NULL,
criado_em DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS produtos (
id INT AUTO_INCREMENT PRIMARY KEY,
loja_id INT NOT NULL,
titulo VARCHAR(200) NOT NULL,
descricao TEXT,
preco DECIMAL(10,2) NOT NULL,
preco_promocional DECIMAL(10,2) DEFAULT NULL,
imagem VARCHAR(255) DEFAULT NULL,
url VARCHAR(255) DEFAULT NULL,
criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT fk_produto_loja FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS cupons (
id INT AUTO_INCREMENT PRIMARY KEY,
loja_id INT NOT NULL,
codigo VARCHAR(80) NOT NULL,
descricao VARCHAR(255) DEFAULT NULL,
desconto_tipo ENUM('percent','valor') NOT NULL DEFAULT 'percent',
desconto_valor DECIMAL(10,2) NOT NULL DEFAULT 0.00,
valido_de DATE DEFAULT NULL,
valido_ate DATE DEFAULT NULL,
usos INT NOT NULL DEFAULT 0,
limite_usos INT DEFAULT NULL,
ativo TINYINT(1) NOT NULL DEFAULT 1,
criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_cupom_loja FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE,
INDEX idx_cupons_valido_ate (valido_ate)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS estatisticas (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
tipo ENUM('visita','clique','compra','cupom') NOT NULL,
ref_id INT DEFAULT NULL,
criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
meta_json JSON DEFAULT NULL,
INDEX idx_tipo_data (tipo, criado_em)
('compra', 2, DATE_SUB(NOW(), INTERVAL 1 DAY));